site_name: Reuse
markdown_extensions:
  - codehilite
theme:
  name: 'material'
pages:
  - QUICK START:
    - Introduction: index.md
    - Props and State: quick-start/props-and-state.md
    - Handling Events: quick-start/handling-events.md
    - Lifecycle: quick-start/lifecycle.md
    - Global State: quick-start/global-state.md