site_name: Reuse
markdown_extensions:
  - codehilite
theme:
  name: 'material'
pages:
  - Get Started: index.md
  - Props: props.md
  - Interaction: interaction.md
  - Component State: component-state.md
  - Lifecycle: lifecycle.md
  - Global Store: global-store.md