site_name: Lemni
site_description: A functional and reactive framework on top of React. Embrace asynchronicity!
repo_url: https://github.com/italonascimento/lemni
edit_uri: edit/master/docs/docs/
markdown_extensions:
  - codehilite
theme:
  name: 'material'
google_analytics:
  - 'UA-115771307-1'
  - 'auto'
pages:
  - INTRODUCTION:
    - What is Lemni?: index.md
  - QUICK START:
    - Installation: quick-start/installation.md
    - Component's Structure: quick-start/components-structure.md
    - Props and State: quick-start/props-and-state.md
    - Handling Events: quick-start/handling-events.md
    - Lifecycle: quick-start/lifecycle.md
    - Global State (Store): quick-start/global-state.md
    - Side Effects: quick-start/side-effects.md