site_name: Lemni
markdown_extensions:
  - codehilite
theme:
  name: 'material'
pages:
  - INTRODUCTION:
    - What is Lemni?: index.md
  - QUICK START:
    - Installation: quick-start/installation.md
    - Component's Structure: quick-start/components-structure.md
    - Props and State: quick-start/props-and-state.md
    - Handling Events: quick-start/handling-events.md
    - Lifecycle: quick-start/lifecycle.md
    - Global State (Store): quick-start/global-state.md
    - Side Effects: quick-start/side-effects.md